#!/bin/bash
# search_home.sh: a example proof of query against /gallery/contemporary-art/caroline-adams
curl -XGET "http://${SERVER}:${ES_PORT}/callowayart/art/_search?pretty" -d '
{
// Returns term aggregation on document.tags for documents not matching
// strings defined in "tags" argument 
  

  "size" : 10,

  "query": { "bool": {
    "must": { "term": {  "__tags" : "contemporary-art"  }},
    "must": { "term": {  "__tags" : "caroline-adams"  }},

    "must_not": { "term": { "__tags" : "exhibit" }},
    "must_not": { "term": { "__tags" : "backendonly" }}
  }},
  


  // provide our group by (aggregations in elastic search)
  "aggregations": {  
    "tags": {
      "terms": { 
        "field":"__tags",
        "min_doc_count": 2,
        "exclude": "exhibit",
        "size": 100
      },

      "aggregations": {

        "last_name": {
          "terms": { 
            "field":"artist_last_name", 
            "size": 1
          }
        },

        // we set artist and description to two; we can deduce 
        // that if there is only a single artist for a group
        // then we are in an artists collection
        "artist_description": {
          "terms": { 
            "field":"artist_description", 
            "size": 2 
          }
        },     

        "artist": {
          "terms": { 
            "field":"__artist", 
            "size": 2
          }
        },             

        "image": {
          "terms": { 
            "field":"uri", 
            "size": 1   
          }
        },

        "thumb": {
          "terms": { 
            "field":"thumb"   
          }
        },   

        "thumb_constrained_width": {
          "terms": { 
            "field":"constrainedw"   
          }
        }            

      }
    }
  }
}
'
