#!/usr/bin/env ruby
require 'elasticsearch'
require 'pp'
require 'erb'
require 'ostruct'

# create es client
client = Elasticsearch::Client.new
name   = 'artists'
params = { tags: [
  'contemporary-art',
]}

# parse statement file and return client
# result
erb = ERB.new(
  content = File.read(
    "#{ENV['RAILS_ROOT']}/db/elasticsearch/statements/" +
    "#{name}.json.erb"
  )
)
statement = erb.result OpenStruct.new(params).instance_eval { 
  binding 
}


# finally return
result = client.search index: 'callowayart', 
                       body:  statement

pp result  