#!/usr/bin/env ruby
# author:      christian calloway callowaylc@gmail.com
# description: runs/restarts rails/unicorn server
# usage:       ./run/unicorn


# constants
##########################################

NEWLINE = "\n"
SPACE   = ' '

# main
##########################################

# announce intention of this script
print  "Restarting Unicorn.."

# get current rails master process id and kill
# if found
if ( ps = `ps aux | grep rails` ) =~ /rails master/
  ps.split( NEWLINE ).each do | line |
    if line =~ /rails master/
      `kill -9 #{ line.split( SPACE )[1] }`
    end
  end
end

# restar rails server and daemonize
puts `rails s -d`

# accounce finish and exit with success
puts 'done'
exit 0