#!/bin/sh
# author:      christian calloway callowaylc@gmail.com
# description: runs/restarts rails/unicorn server
# usage:       ./run/unicorn

pid=`cat $RAILS_ROOT/tmp/pids/unicorn.pid`
echo "Restarting Unicorn ($unicorn_pid)"
kill -HUP $unicorn_pid

cd $RAILS_ROOT && rails s -d
